BaseUrl= "https://cyx20080216.github.io/blog/"
LanguageCode= "zh-CN"
Title= "cyx20080216"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "syui"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "一位OIer的个人博客"
  cover = "images/user.jpg"
  author = "cyx20080216"
  authorlocation = "China, Hunan"
  authorwebsite = "https://cyx20080216.github.io/blog/"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
