name: Auto green

#on:
#  push:
#    branches:
#      - master
#  schedule:
#    - cron: "* * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Push
        run: |
          git config --local user.email "cyx20080216@qq.com"
          git config --local user.name "cyx20080216"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Auto green."
          git push
